// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/404": {
    params: {};
  };
  "/": {
    params: {};
  };
  "/kontakt": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/produkte/:slug": {
    params: {
      "slug": string;
    };
  };
  "/impressum": {
    params: {};
  };
  "/datenschutz": {
    params: {};
  };
  "/agb": {
    params: {};
  };
  "/lizenzen": {
    params: {};
  };
  "/admin/login": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/edit/:slug": {
    params: {
      "slug": string;
    };
  };
  "/admin/users": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "./app/routes/system/infrastructure/NotFound.tsx": {
    id: "404";
    page: "/404";
  } | {
    id: "*";
    page: "/*";
  };
  "root.tsx": {
    id: "root";
    page: "/404" | "/" | "/kontakt" | "/blog/:slug" | "/produkte/:slug" | "/impressum" | "/datenschutz" | "/agb" | "/lizenzen" | "/admin/login" | "/admin/dashboard" | "/admin/edit/:slug" | "/admin/users" | "/*";
  };
  "./app/routes/app/Home.tsx": {
    id: "app/routes/app/Home";
    page: "/";
  };
  "./app/routes/app/Contact.tsx": {
    id: "kontakt";
    page: "/kontakt";
  };
  "./app/routes/app/BlogPost.tsx": {
    id: "blog--slug";
    page: "/blog/:slug";
  };
  "./app/routes/app/ProductPage.tsx": {
    id: "produkte--slug";
    page: "/produkte/:slug";
  };
  "./app/routes/system/legal/LegalPage.tsx": {
    id: "impressum";
    page: "/impressum";
  } | {
    id: "datenschutz";
    page: "/datenschutz";
  } | {
    id: "agb";
    page: "/agb";
  } | {
    id: "lizenzen";
    page: "/lizenzen";
  };
  "./app/routes/system/admin/AdminLogin.tsx": {
    id: "admin-login";
    page: "/admin/login";
  };
  "./app/routes/system/admin/AdminDashboard.tsx": {
    id: "admin-dashboard";
    page: "/admin/dashboard";
  };
  "./app/routes/system/admin/AdminEditPage.tsx": {
    id: "admin-edit--slug";
    page: "/admin/edit/:slug";
  };
  "./app/routes/system/admin/AdminUsersPage.tsx": {
    id: "admin-users";
    page: "/admin/users";
  };
};

type RouteModules = {
  "404": typeof import("./src/./app/routes/system/infrastructure/NotFound.tsx");
  "root": typeof import("./src/root.tsx");
  "app/routes/app/Home": typeof import("./src/./app/routes/app/Home.tsx");
  "kontakt": typeof import("./src/./app/routes/app/Contact.tsx");
  "blog--slug": typeof import("./src/./app/routes/app/BlogPost.tsx");
  "produkte--slug": typeof import("./src/./app/routes/app/ProductPage.tsx");
  "impressum": typeof import("./src/./app/routes/system/legal/LegalPage.tsx");
  "datenschutz": typeof import("./src/./app/routes/system/legal/LegalPage.tsx");
  "agb": typeof import("./src/./app/routes/system/legal/LegalPage.tsx");
  "lizenzen": typeof import("./src/./app/routes/system/legal/LegalPage.tsx");
  "admin-login": typeof import("./src/./app/routes/system/admin/AdminLogin.tsx");
  "admin-dashboard": typeof import("./src/./app/routes/system/admin/AdminDashboard.tsx");
  "admin-edit--slug": typeof import("./src/./app/routes/system/admin/AdminEditPage.tsx");
  "admin-users": typeof import("./src/./app/routes/system/admin/AdminUsersPage.tsx");
  "*": typeof import("./src/./app/routes/system/infrastructure/NotFound.tsx");
};